#!/usr/bin/env bash

menu (){
	cat << EOF 
"---------GIT INTEGRATION WITH LAZARUS-------------------
	
		1)      Open Lazarus Project
		2)      View Status
		3)      Add Modified Changes
		4)      Commit
		5)      Push Project
		6)      Pull Project
		7)      Edit .gitignore
		8)      Stash
		9)      Stash Restore
		10)     Stash List
		0, q)   Exit
		
--------------------------------------------------------" 
EOF
}

press_any_key(){
	echo ""
	read -p "Press any Key for return the main menu"
}

while :; do
	clear
	
	menu
	read -p "Option: " option

	case $option in
	#Open Lazarus Project
	1)
		lazarus-ide nfl_stats.lpi;;
		
	#View Status
	2)
		git status
		
		press_any_key;;
		
	#Add Modified Files
	3)
		git add .
		
		press_any_key;;
		
	#Commit
	4)
		git commit -m "Update"
		
		press_any_key;;
		
	#Push Project
	5)
		git push origin main
		
		press_any_key;;
		
	#Pull Project
	6)
		git pull origin main
		
		press_any_key;;
		
	#Edit .gitignore
	7)
		vim .gitignore
		
		press_any_key;;

    #Stash
	8)
		git stash
		
		press_any_key;;

    #Stash Restore
	9)
		read -p "Choose the ID: " stash_id
		git stash apply stash@{$stash_id}
		
		press_any_key;;

    #Stash List
	10)
		git stash list
		
		press_any_key;;

    #Exit Script
	0)
		exit 0;;

    q)
        exit 0;;

    *)
        echo "Invalid Option"
        sleep 2;;
		
	esac;

done;
